# Generated by Django 5.0.4 on 2024-04-27 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='title',
            new_name='name',
        ),
    ]
