# Generated by Django 5.0.4 on 2024-04-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General Skincare', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
