# Generated by Django 5.0.4 on 2024-04-29 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_product_category_product_directions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AT', 'Acne Treatments'), ('C', 'Cleansers'), ('E', 'Exfoliants'), ('EC', 'Eye Care'), ('FM', 'Face Masks'), ('FO', 'Face Oils'), ('FP', 'Facial Peels'), ('L', 'Lip Care'), ('M', 'Moisturizers'), ('S', 'Serums'), ('SS', 'Sunscreen'), ('T', 'Toners')], default='AT', max_length=2),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
    ]
