# Generated by Django 5.0.4 on 2024-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_type',
            field=models.CharField(blank=True, default='Undefined', max_length=30),
        ),
        migrations.CreateModel(
            name='SuggestedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('AT', 'Acne Treatments'), ('C', 'Cleansers'), ('E', 'Exfoliants'), ('EC', 'Eye Care'), ('FM', 'Face Masks'), ('FO', 'Face Oils'), ('FP', 'Facial Peels'), ('L', 'Lip Care'), ('M', 'Moisturizers'), ('S', 'Serums'), ('SS', 'Sunscreen'), ('T', 'Toners')], default='AT', max_length=2)),
                ('skin_type', models.ManyToManyField(to='main_app.skintype')),
            ],
        ),
    ]
