# Generated by Django 5.0.4 on 2024-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_profile_skin_type_suggestedproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedproduct',
            old_name='skin_type',
            new_name='skin_types',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='suggestedproduct',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
