# Generated by Django 5.0.4 on 2024-05-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_skin_type_suggestedproduct_skin_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedproduct',
            name='brand',
            field=models.CharField(default='Generic', max_length=50),
        ),
    ]
