# Generated by Django 5.0.4 on 2024-05-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_suggestedproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedproduct',
            name='image',
        ),
    ]
