# Generated by Django 5.0.4 on 2024-05-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_suggestedproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='suggested_products/'),
        ),
    ]
