# Generated by Django 5.0.4 on 2024-05-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_suggestedproduct_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_type',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
