# Generated by Django 5.0.4 on 2024-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_profile_skin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suitable_for',
            field=models.ManyToManyField(blank=True, to='main_app.skintype'),
        ),
    ]
